bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '1000000': '$1000,000',
    '2000000': '$2000,000',
    '3000000': '$3000,000',
    '4000000': '$4000,000',
    '5000000': '$5000,000',
    '6000000': '$6000,000',
    '7000000': '$7000,000',
    '8000000': '$8000,000',
    '9000000': '$9000,000',
    '10000000': '$1M+',
}

state_choices = {
        "AL": 'Alabama',
        "AK": 'Alaska',
        "AZ": 'Arizona',
        "AR": 'Arkansas',
        "CA": 'California',
        "CO": 'Colorado',
        "CT": 'Connecticut',
        "DE": 'Delaware',
        "DC": 'District Of Columbia',
        "FL": 'Florida',
        "GA": 'Georgia',
        "HI": 'Hawaii',
        "ID": 'Idaho',
        "IL": 'Illinois',
        "IN": 'Indiana',
        "IA": 'Iowa',
        "KS": 'Kansas',
        "KY": 'Kentucky',
        "LA": 'Louisiana',
        "ME": 'Maine',
        "MD": 'Maryland',
        "MA": 'Massachusetts',
        "MI": 'Michigan',
        "MN": 'Minnesota',
        "MS": 'Mississippi',
        "MO": 'Missouri',
        "MT": 'Montana',
        "NE": 'Nebraska',
        "NV": 'Nevada',
        "NH": 'New Hampshire',
        "NJ": 'New Jersey',
        "NM": 'New Mexico',
        "NY": 'New York',
        "NC": 'North Carolina',
        "ND": 'North Dakota',
        "OH": 'Ohio',
        "OK": 'Oklahoma',
        "OR": 'Oregon',
        "PA": 'Pennsylvania',
        "RI": 'Rhode Island',
        "SC": 'South Carolina',
        "SD": 'South Dakota',
        "TN": 'Tennessee',
        "TX": 'Texas',
        "UT": 'Utah',
        "VT": 'Vermont',
        "VA": 'Virginia',
        "WA": 'Washington',
        "WV": 'West Virginia',
        "WI": 'Wisconsin',
        "WY": 'Wyoming'
}